//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace r3mus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastWeeksMailStat
    {
        public Nullable<long> Id { get; set; }
        public string Mailer { get; set; }
        public Nullable<int> Mailed { get; set; }
    }
}
