//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace r3mus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecruitmentStatEntities : DbContext
    {
        public RecruitmentStatEntities()
            : base("name=RecruitmentStatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LastWeeksMailStat> LastWeeksMailStats { get; set; }
        public virtual DbSet<LastWeeksSubmissionStat> LastWeeksSubmissionStats { get; set; }
    }
}
