//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hipchat_Plugin_TestHarness.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"killID\":\"45872314\",\"solarSystemID\":\"30003805\",\"killTime\":\"2015-04-10 00:24:00\"" +
            ",\"moonID\":\"0\",\"victim\":{\"shipTypeID\":\"17715\",\"damageTaken\":\"24673\",\"factionName\"" +
            ":\"\",\"factionID\":\"0\",\"allianceName\":\"\",\"allianceID\":\"0\",\"corporationName\":\"New Ca" +
            "ldari Bureau of Investigation\",\"corporationID\":\"98389102\",\"characterName\":\"Fisty" +
            "McBumBardier\",\"characterID\":\"1905379957\",\"victim\":\"\"},\"attackers\":[{\"characterID" +
            "\":\"95150561\",\"characterName\":\"Raegar Katelo\",\"corporationID\":\"1000009\",\"corporat" +
            "ionName\":\"Caldari Provisions\",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\"" +
            ",\"factionName\":\"\",\"securityStatus\":\"1.69879300518658\",\"damageDone\":\"4734\",\"final" +
            "Blow\":\"1\",\"weaponTypeID\":\"7367\",\"shipTypeID\":\"16227\"},{\"characterID\":\"344287599\"" +
            ",\"characterName\":\"SevereTorture\",\"corporationID\":\"98382245\",\"corporationName\":\"G" +
            "ypsy Thieves and Pickpockets\",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\"" +
            ",\"factionName\":\"\",\"securityStatus\":\"-2.7\",\"damageDone\":\"5718\",\"finalBlow\":\"0\",\"w" +
            "eaponTypeID\":\"2488\",\"shipTypeID\":\"16227\"},{\"characterID\":\"92279330\",\"characterNa" +
            "me\":\"Asa Yazria\",\"corporationID\":\"98384907\",\"corporationName\":\"FANHAUS\",\"allianc" +
            "eID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"0." +
            "7\",\"damageDone\":\"3541\",\"finalBlow\":\"0\",\"weaponTypeID\":\"7367\",\"shipTypeID\":\"16227" +
            "\"},{\"characterID\":\"1044538148\",\"characterName\":\"Tiberius Mal\",\"corporationID\":\"9" +
            "8389365\",\"corporationName\":\"Raised By Wolves Inc\",\"allianceID\":\"0\",\"allianceName" +
            "\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"2\",\"damageDone\":\"2072\",\"" +
            "finalBlow\":\"0\",\"weaponTypeID\":\"24702\",\"shipTypeID\":\"24702\"},{\"characterID\":\"3130" +
            "14419\",\"characterName\":\"Arsonator\",\"corporationID\":\"98324672\",\"corporationName\":" +
            "\"The Shadow Valkyries\",\"allianceID\":\"99005176\",\"allianceName\":\"Blackout Operatio" +
            "ns\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"-1.9\",\"damageDone\":\"1936\"" +
            ",\"finalBlow\":\"0\",\"weaponTypeID\":\"16227\",\"shipTypeID\":\"16227\"},{\"characterID\":\"13" +
            "83148225\",\"characterName\":\"Ranger40Z\",\"corporationID\":\"98092747\",\"corporationNam" +
            "e\":\"Infinity Engine\",\"allianceID\":\"99002913\",\"allianceName\":\"Sleeping Dragons\",\"" +
            "factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"-1.9\",\"damageDone\":\"1925\",\"fin" +
            "alBlow\":\"0\",\"weaponTypeID\":\"2488\",\"shipTypeID\":\"16227\"},{\"characterID\":\"95380409" +
            "\",\"characterName\":\"Kotef Khardula\",\"corporationID\":\"98338178\",\"corporationName\":" +
            "\"CroGi\",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"sec" +
            "urityStatus\":\"2.8\",\"damageDone\":\"1816\",\"finalBlow\":\"0\",\"weaponTypeID\":\"24696\",\"s" +
            "hipTypeID\":\"24696\"},{\"characterID\":\"866421452\",\"characterName\":\"Shadowace Evi\",\"" +
            "corporationID\":\"98338178\",\"corporationName\":\"CroGi\",\"allianceID\":\"0\",\"allianceNa" +
            "me\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"4.3\",\"damageDone\":\"178" +
            "5\",\"finalBlow\":\"0\",\"weaponTypeID\":\"2456\",\"shipTypeID\":\"16229\"},{\"characterID\":\"3" +
            "27391351\",\"characterName\":\"ton pentre\",\"corporationID\":\"98330922\",\"corporationNa" +
            "me\":\"lonestar tactical incorperated\",\"allianceID\":\"0\",\"allianceName\":\"\",\"faction" +
            "ID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"2.9\",\"damageDone\":\"944\",\"finalBlow\":\"" +
            "0\",\"weaponTypeID\":\"24696\",\"shipTypeID\":\"24696\"},{\"characterID\":\"92709353\",\"chara" +
            "cterName\":\"happy genocide\",\"corporationID\":\"1287319632\",\"corporationName\":\"Shado" +
            "w of Darkness\",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":" +
            "\"\",\"securityStatus\":\"2.3\",\"damageDone\":\"133\",\"finalBlow\":\"0\",\"weaponTypeID\":\"248" +
            "8\",\"shipTypeID\":\"631\"},{\"characterID\":\"490956277\",\"characterName\":\"Major Theef\"," +
            "\"corporationID\":\"98340372\",\"corporationName\":\"SUPREME MATHEMATICS\",\"allianceID\":" +
            "\"99004295\",\"allianceName\":\"A Band Apart.\",\"factionID\":\"0\",\"factionName\":\"\",\"secu" +
            "rityStatus\":\"-1.2\",\"damageDone\":\"69\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19814\",\"shi" +
            "pTypeID\":\"634\"},{\"characterID\":\"90516354\",\"characterName\":\"FeroxLn Inkura\",\"corp" +
            "orationID\":\"98320515\",\"corporationName\":\"In The Year 3000\",\"allianceID\":\"0\",\"all" +
            "ianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"-0.8\",\"damageDo" +
            "ne\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"3520\",\"shipTypeID\":\"24696\"},{\"characterI" +
            "D\":\"1430562964\",\"characterName\":\"Smogscreen\",\"corporationID\":\"1273124967\",\"corpo" +
            "rationName\":\"Very Drunken Eve Flying Instructors\",\"allianceID\":\"1459096720\",\"all" +
            "ianceName\":\"Brotherhood Of Silent Space\",\"factionID\":\"0\",\"factionName\":\"\",\"secur" +
            "ityStatus\":\"-0.2\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"3512\",\"shipTy" +
            "peID\":\"24696\"},{\"characterID\":\"95465285\",\"characterName\":\"Thrushie Mcmoisty Defu" +
            "ngal\",\"corporationID\":\"1000077\",\"corporationName\":\"Royal Amarr Institute\",\"allia" +
            "nceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"" +
            "-0.5\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"5299\",\"shipTypeID\":\"609\"}" +
            ",{\"characterID\":\"93349849\",\"characterName\":\"WiskeySeiera Echo9er\",\"corporationID" +
            "\":\"98354331\",\"corporationName\":\"Down Time Renegades\",\"allianceID\":\"0\",\"allianceN" +
            "ame\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"5\",\"damageDone\":\"0\",\"" +
            "finalBlow\":\"0\",\"weaponTypeID\":\"23707\",\"shipTypeID\":\"11985\"},{\"characterID\":\"9082" +
            "3453\",\"characterName\":\"Blunted Blazer\",\"corporationID\":\"98356422\",\"corporationNa" +
            "me\":\"Full Spectrum Inc\",\"allianceID\":\"99003549\",\"allianceName\":\"Greater Western " +
            "Co-Prosperity Sphere\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"-1.7\",\"" +
            "damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19814\",\"shipTypeID\":\"16231\"},{\"c" +
            "haracterID\":\"92237210\",\"characterName\":\"MurinA 7o9\",\"corporationID\":\"98383454\",\"" +
            "corporationName\":\"Slumbered For Millennia\",\"allianceID\":\"0\",\"allianceName\":\"\",\"f" +
            "actionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"-4\",\"damageDone\":\"0\",\"finalBlow" +
            "\":\"0\",\"weaponTypeID\":\"11198\",\"shipTypeID\":\"11198\"}],\"items\":[{\"typeID\":\"19339\",\"" +
            "flag\":\"19\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"4405\"" +
            ",\"flag\":\"12\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"216" +
            "40\",\"flag\":\"87\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"2\",\"singleton\":\"0\"},{\"typeID\":\"" +
            "27387\",\"flag\":\"5\",\"qtyDropped\":\"700\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeI" +
            "D\":\"4475\",\"flag\":\"31\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typ" +
            "eID\":\"32780\",\"flag\":\"21\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"" +
            "typeID\":\"27361\",\"flag\":\"5\",\"qtyDropped\":\"2679\",\"qtyDestroyed\":\"0\",\"singleton\":\"0" +
            "\"},{\"typeID\":\"8089\",\"flag\":\"29\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":" +
            "\"0\"},{\"typeID\":\"17559\",\"flag\":\"24\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleto" +
            "n\":\"0\"},{\"typeID\":\"24417\",\"flag\":\"20\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singl" +
            "eton\":\"0\"},{\"typeID\":\"4395\",\"flag\":\"92\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"sin" +
            "gleton\":\"0\"},{\"typeID\":\"27371\",\"flag\":\"29\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"34\"," +
            "\"singleton\":\"0\"},{\"typeID\":\"4405\",\"flag\":\"14\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0" +
            "\",\"singleton\":\"0\"},{\"typeID\":\"4475\",\"flag\":\"30\",\"qtyDropped\":\"0\",\"qtyDestroyed\":" +
            "\"1\",\"singleton\":\"0\"},{\"typeID\":\"5839\",\"flag\":\"11\",\"qtyDropped\":\"0\",\"qtyDestroyed" +
            "\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"27371\",\"flag\":\"28\",\"qtyDropped\":\"0\",\"qtyDestro" +
            "yed\":\"34\",\"singleton\":\"0\"},{\"typeID\":\"8089\",\"flag\":\"27\",\"qtyDropped\":\"1\",\"qtyDes" +
            "troyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"3841\",\"flag\":\"22\",\"qtyDropped\":\"0\",\"qtyD" +
            "estroyed\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"2175\",\"flag\":\"87\",\"qtyDropped\":\"0\",\"qt" +
            "yDestroyed\":\"2\",\"singleton\":\"0\"},{\"typeID\":\"32006\",\"flag\":\"5\",\"qtyDropped\":\"0\",\"" +
            "qtyDestroyed\":\"14\",\"singleton\":\"0\"},{\"typeID\":\"15891\",\"flag\":\"23\",\"qtyDropped\":\"" +
            "0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"2185\",\"flag\":\"87\",\"qtyDropped\"" +
            ":\"2\",\"qtyDestroyed\":\"2\",\"singleton\":\"0\"},{\"typeID\":\"28668\",\"flag\":\"5\",\"qtyDroppe" +
            "d\":\"105\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"31185\",\"flag\":\"94\",\"qtyD" +
            "ropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"27371\",\"flag\":\"5\",\"qt" +
            "yDropped\":\"140\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"4405\",\"flag\":\"13\"" +
            ",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"31718\",\"flag\":\"" +
            "93\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"27371\",\"flag" +
            "\":\"27\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"34\",\"singleton\":\"0\"},{\"typeID\":\"15610\",\"" +
            "flag\":\"5\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"2\",\"singleton\":\"0\"},{\"typeID\":\"8089\"," +
            "\"flag\":\"28\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"}],\"zkb\":{\"totalV" +
            "alue\":\"599308021.28\",\"points\":\"4\",\"source\":\"CREST\",\"hash\":\"86974e93bbc60b9b8a4c8" +
            "ca30b76ad5a624d50b1\"}},{\"killID\":\"45871918\",\"solarSystemID\":\"30003796\",\"killTime" +
            "\":\"2015-04-09 23:58:00\",\"moonID\":\"0\",\"victim\":{\"shipTypeID\":\"11129\",\"damageTaken" +
            "\":\"457\",\"factionName\":\"\",\"factionID\":\"0\",\"allianceName\":\"\",\"allianceID\":\"0\",\"cor" +
            "porationName\":\"Chesthair Waves When The Wind Blows\",\"corporationID\":\"98386001\",\"" +
            "characterName\":\"Touchie Mc TwiddleHands\",\"characterID\":\"93087396\",\"victim\":\"\"},\"" +
            "attackers\":[{\"characterID\":\"1044538148\",\"characterName\":\"Tiberius Mal\",\"corporat" +
            "ionID\":\"98389365\",\"corporationName\":\"Raised By Wolves Inc\",\"allianceID\":\"0\",\"all" +
            "ianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"2.3275386485486" +
            "\",\"damageDone\":\"457\",\"finalBlow\":\"1\",\"weaponTypeID\":\"2969\",\"shipTypeID\":\"24702\"}" +
            ",{\"characterID\":\"90823453\",\"characterName\":\"Blunted Blazer\",\"corporationID\":\"983" +
            "56422\",\"corporationName\":\"Full Spectrum Inc\",\"allianceID\":\"99003549\",\"allianceNa" +
            "me\":\"Greater Western Co-Prosperity Sphere\",\"factionID\":\"0\",\"factionName\":\"\",\"sec" +
            "urityStatus\":\"-1.7\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19814\",\"shi" +
            "pTypeID\":\"16231\"},{\"characterID\":\"94101683\",\"characterName\":\"Caribou apex\",\"corp" +
            "orationID\":\"98033026\",\"corporationName\":\"Blitzkrieg.\",\"allianceID\":\"150097440\",\"" +
            "allianceName\":\"Get Off My Lawn\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus" +
            "\":\"4.7\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"7171\",\"shipTypeID\":\"430" +
            "2\"}],\"items\":[],\"zkb\":{\"totalValue\":\"20497.85\",\"points\":\"1\",\"source\":\"CREST\",\"ha" +
            "sh\":\"aafe53475a613ea9c03f8025b87cda48aa894667\"}},{\"killID\":45864898,\"solarSystem" +
            "ID\":30003726,\"killTime\":\"2015-04-09 18:55:00\",\"moonID\":0,\"victim\":{\"shipTypeID\":" +
            "29990,\"characterID\":1519352763,\"characterName\":\"PIXSE\",\"corporationID\":112702028" +
            ",\"corporationName\":\"Volition Cult\",\"allianceID\":240835459,\"allianceName\":\"The Vo" +
            "lition Cult\",\"factionID\":0,\"factionName\":\"\",\"damageTaken\":22617},\"attackers\":[{\"" +
            "characterID\":1292695461,\"characterName\":\"Mr Morimoto\",\"corporationID\":98329794,\"" +
            "corporationName\":\"Solar Sails\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"f" +
            "actionName\":\"\",\"securityStatus\":-1.4,\"damageDone\":3188,\"finalBlow\":0,\"weaponType" +
            "ID\":27359,\"shipTypeID\":12034},{\"characterID\":92680254,\"characterName\":\"BUBAKAR M" +
            "AHAHA\",\"corporationID\":867072006,\"corporationName\":\"The Real OC\",\"allianceID\":99" +
            "004887,\"allianceName\":\"ROC.\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-1." +
            "3,\"damageDone\":2550,\"finalBlow\":0,\"weaponTypeID\":24519,\"shipTypeID\":12034},{\"cha" +
            "racterID\":95004823,\"characterName\":\"Rahkesh Harshmallows\",\"corporationID\":983783" +
            "37,\"corporationName\":\"HC - Thirteen Enterprises\",\"allianceID\":0,\"allianceName\":\"" +
            "\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-0.6,\"damageDone\":2262,\"finalB" +
            "low\":0,\"weaponTypeID\":27351,\"shipTypeID\":11377},{\"characterID\":939625659,\"charac" +
            "terName\":\"Ismail Third\",\"corporationID\":98385030,\"corporationName\":\"Nasheed Appr" +
            "eciation Station\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"" +
            "\",\"securityStatus\":5,\"damageDone\":2167,\"finalBlow\":1,\"weaponTypeID\":27359,\"shipT" +
            "ypeID\":12034},{\"characterID\":92322922,\"characterName\":\"Dr Draxxx\",\"corporationID" +
            "\":98203328,\"corporationName\":\"Sanctuary of Shadows\",\"allianceID\":0,\"allianceName" +
            "\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-1.7,\"damageDone\":1637,\"fin" +
            "alBlow\":0,\"weaponTypeID\":27345,\"shipTypeID\":12032},{\"characterID\":108115856,\"cha" +
            "racterName\":\"virxens\",\"corporationID\":98226285,\"corporationName\":\"Nexis.\",\"allia" +
            "nceID\":99004785,\"allianceName\":\"TCC.\",\"factionID\":0,\"factionName\":\"\",\"securitySt" +
            "atus\":-0.3,\"damageDone\":1580,\"finalBlow\":0,\"weaponTypeID\":8117,\"shipTypeID\":1203" +
            "4},{\"characterID\":90149862,\"characterName\":\"Nytoxias\",\"corporationID\":98097120,\"" +
            "corporationName\":\"ISB Banner Interstellar Operations\",\"allianceID\":0,\"allianceNa" +
            "me\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":3.3,\"damageDone\":1200,\"fi" +
            "nalBlow\":0,\"weaponTypeID\":27359,\"shipTypeID\":12034},{\"characterID\":93574604,\"cha" +
            "racterName\":\"Tipa Riot\",\"corporationID\":1000168,\"corporationName\":\"Federal Navy " +
            "Academy\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securi" +
            "tyStatus\":-2.2,\"damageDone\":1110,\"finalBlow\":0,\"weaponTypeID\":27339,\"shipTypeID\"" +
            ":12038},{\"characterID\":93401488,\"characterName\":\"Noria Odunen\",\"corporationID\":9" +
            "8387394,\"corporationName\":\"100 Deadly Sins\",\"allianceID\":0,\"allianceName\":\"\",\"fa" +
            "ctionID\":0,\"factionName\":\"\",\"securityStatus\":3.3,\"damageDone\":1046,\"finalBlow\":0" +
            ",\"weaponTypeID\":27359,\"shipTypeID\":12034},{\"characterID\":94939025,\"characterName" +
            "\":\"Peter \'Littlefinger\' Baelish\",\"corporationID\":98347696,\"corporationName\":\"Ser" +
            "ious Internet Spaceship Buisness\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0" +
            ",\"factionName\":\"\",\"securityStatus\":-0.1,\"damageDone\":928,\"finalBlow\":0,\"weaponTy" +
            "peID\":27345,\"shipTypeID\":12032},{\"characterID\":94880891,\"characterName\":\"Rion Ho" +
            "lliday\",\"corporationID\":98328974,\"corporationName\":\"Phoenix Naval Academy\",\"alli" +
            "anceID\":99004604,\"allianceName\":\"Phoenix Naval Systems\",\"factionID\":0,\"factionNa" +
            "me\":\"\",\"securityStatus\":1.3,\"damageDone\":854,\"finalBlow\":0,\"weaponTypeID\":27345," +
            "\"shipTypeID\":12032},{\"characterID\":1392600597,\"characterName\":\"Angi Tulo\",\"corpo" +
            "rationID\":98389365,\"corporationName\":\"Raised By Wolves Inc\",\"allianceID\":0,\"alli" +
            "anceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":0.3,\"damageDone\":78" +
            "3,\"finalBlow\":0,\"weaponTypeID\":27351,\"shipTypeID\":11377},{\"characterID\":94220967" +
            ",\"characterName\":\"Rar Fox\",\"corporationID\":98288683,\"corporationName\":\"Umbra Syn" +
            "dicate\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securit" +
            "yStatus\":0.7,\"damageDone\":714,\"finalBlow\":0,\"weaponTypeID\":27345,\"shipTypeID\":12" +
            "032},{\"characterID\":92254528,\"characterName\":\"Chris Virens\",\"corporationID\":9815" +
            "1305,\"corporationName\":\"Vril Corp.\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\"" +
            ":0,\"factionName\":\"\",\"securityStatus\":-1.1,\"damageDone\":663,\"finalBlow\":0,\"weapon" +
            "TypeID\":27351,\"shipTypeID\":11377},{\"characterID\":90676720,\"characterName\":\"Hugh " +
            "Knight\",\"corporationID\":98295759,\"corporationName\":\"Usque Ad Mortem\",\"allianceID" +
            "\":99004785,\"allianceName\":\"TCC.\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\"" +
            ":0.1,\"damageDone\":565,\"finalBlow\":0,\"weaponTypeID\":24525,\"shipTypeID\":11377},{\"c" +
            "haracterID\":94522777,\"characterName\":\"SikulaCZ\",\"corporationID\":1285989187,\"corp" +
            "orationName\":\"STARS of BABYLON ALLIANCE\",\"allianceID\":466862619,\"allianceName\":\"" +
            "CZECH Alliance\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-2,\"damageDone\":" +
            "457,\"finalBlow\":0,\"weaponTypeID\":27351,\"shipTypeID\":11377},{\"characterID\":417481" +
            "089,\"characterName\":\"drraventlwml\",\"corporationID\":98082962,\"corporationName\":\"S" +
            "everasse Mining\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\"" +
            ",\"securityStatus\":4.9,\"damageDone\":425,\"finalBlow\":0,\"weaponTypeID\":8117,\"shipTy" +
            "peID\":12034},{\"characterID\":93051312,\"characterName\":\"Romaz Chechen\",\"corporatio" +
            "nID\":98273077,\"corporationName\":\"boobies and kittens\",\"allianceID\":0,\"allianceNa" +
            "me\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-1.3,\"damageDone\":212,\"fi" +
            "nalBlow\":0,\"weaponTypeID\":24523,\"shipTypeID\":12038},{\"characterID\":94526200,\"cha" +
            "racterName\":\"Sarah Faye\",\"corporationID\":98345210,\"corporationName\":\"Pandemic La" +
            "boratories\",\"allianceID\":99004177,\"allianceName\":\"Shadow\'s Edge Alliance\",\"facti" +
            "onID\":0,\"factionName\":\"\",\"securityStatus\":4.8,\"damageDone\":185,\"finalBlow\":0,\"we" +
            "aponTypeID\":27339,\"shipTypeID\":12038},{\"characterID\":94927186,\"characterName\":\"B" +
            "ased Imperator\",\"corporationID\":98287908,\"corporationName\":\"Nanashi no Geemu\",\"a" +
            "llianceID\":99004542,\"allianceName\":\"FOX.HOUND\",\"factionID\":0,\"factionName\":\"\",\"s" +
            "ecurityStatus\":-1.4,\"damageDone\":85,\"finalBlow\":0,\"weaponTypeID\":8117,\"shipTypeI" +
            "D\":12038},{\"characterID\":95145225,\"characterName\":\"ILK Baddies\",\"corporationID\":" +
            "98354230,\"corporationName\":\"Voidlight Consortium\",\"allianceID\":99005190,\"allianc" +
            "eName\":\"Interstellar Solutions\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":" +
            "-3.2,\"damageDone\":6,\"finalBlow\":0,\"weaponTypeID\":33468,\"shipTypeID\":33468},{\"cha" +
            "racterID\":90974906,\"characterName\":\"DANGERUS4U DEAD\",\"corporationID\":98296941,\"c" +
            "orporationName\":\"Freddys Miningcrew\",\"allianceID\":99005061,\"allianceName\":\"Requi" +
            "em for a dream.\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-1.9,\"damageDon" +
            "e\":0,\"finalBlow\":0,\"weaponTypeID\":527,\"shipTypeID\":11963},{\"characterID\":9492070" +
            "9,\"characterName\":\"capt boemernl\",\"corporationID\":98249462,\"corporationName\":\"Un" +
            "kindness Incorporated\",\"allianceID\":99005186,\"allianceName\":\"No Not Believing\",\"" +
            "factionID\":0,\"factionName\":\"\",\"securityStatus\":3.8,\"damageDone\":0,\"finalBlow\":0," +
            "\"weaponTypeID\":19814,\"shipTypeID\":33468}],\"items\":[{\"typeID\":29975,\"flag\":126,\"q" +
            "tyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":12773,\"flag\":29,\"qtyDropp" +
            "ed\":0,\"qtyDestroyed\":77,\"singleton\":0},{\"typeID\":18911,\"flag\":13,\"qtyDropped\":1," +
            "\"qtyDestroyed\":0,\"singleton\":0},{\"typeID\":30133,\"flag\":128,\"qtyDropped\":0,\"qtyDe" +
            "stroyed\":1,\"singleton\":0},{\"typeID\":30066,\"flag\":125,\"qtyDropped\":0,\"qtyDestroye" +
            "d\":1,\"singleton\":0},{\"typeID\":21896,\"flag\":5,\"qtyDropped\":1494,\"qtyDestroyed\":0," +
            "\"singleton\":0},{\"typeID\":12773,\"flag\":30,\"qtyDropped\":77,\"qtyDestroyed\":0,\"singl" +
            "eton\":0},{\"typeID\":2897,\"flag\":30,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0}" +
            ",{\"typeID\":17559,\"flag\":21,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"type" +
            "ID\":12773,\"flag\":28,\"qtyDropped\":77,\"qtyDestroyed\":0,\"singleton\":0},{\"typeID\":16" +
            "273,\"flag\":5,\"qtyDropped\":450,\"qtyDestroyed\":0,\"singleton\":0},{\"typeID\":12773,\"f" +
            "lag\":31,\"qtyDropped\":0,\"qtyDestroyed\":77,\"singleton\":0},{\"typeID\":31059,\"flag\":9" +
            "4,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":12773,\"flag\":5,\"qtyDr" +
            "opped\":0,\"qtyDestroyed\":250,\"singleton\":0},{\"typeID\":18702,\"flag\":12,\"qtyDropped" +
            "\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":31059,\"flag\":93,\"qtyDropped\":0,\"qt" +
            "yDestroyed\":1,\"singleton\":0},{\"typeID\":18690,\"flag\":22,\"qtyDropped\":1,\"qtyDestro" +
            "yed\":0,\"singleton\":0},{\"typeID\":2897,\"flag\":29,\"qtyDropped\":1,\"qtyDestroyed\":0,\"" +
            "singleton\":0},{\"typeID\":17559,\"flag\":20,\"qtyDropped\":1,\"qtyDestroyed\":0,\"singlet" +
            "on\":0},{\"typeID\":20353,\"flag\":15,\"qtyDropped\":1,\"qtyDestroyed\":0,\"singleton\":0}," +
            "{\"typeID\":12773,\"flag\":27,\"qtyDropped\":0,\"qtyDestroyed\":77,\"singleton\":0},{\"type" +
            "ID\":15891,\"flag\":19,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":286" +
            "68,\"flag\":5,\"qtyDropped\":54,\"qtyDestroyed\":0,\"singleton\":0},{\"typeID\":2897,\"flag" +
            "\":27,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":13974,\"flag\":11,\"q" +
            "tyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":2897,\"flag\":28,\"qtyDroppe" +
            "d\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":31059,\"flag\":92,\"qtyDropped\":0,\"q" +
            "tyDestroyed\":1,\"singleton\":0},{\"typeID\":15729,\"flag\":16,\"qtyDropped\":0,\"qtyDestr" +
            "oyed\":1,\"singleton\":0},{\"typeID\":21096,\"flag\":32,\"qtyDropped\":0,\"qtyDestroyed\":1" +
            ",\"singleton\":0},{\"typeID\":30106,\"flag\":129,\"qtyDropped\":0,\"qtyDestroyed\":1,\"sing" +
            "leton\":0},{\"typeID\":15729,\"flag\":14,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":" +
            "0},{\"typeID\":30159,\"flag\":127,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"t" +
            "ypeID\":2897,\"flag\":31,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":2" +
            "488,\"flag\":87,\"qtyDropped\":0,\"qtyDestroyed\":3,\"singleton\":0},{\"typeID\":2488,\"fla" +
            "g\":87,\"qtyDropped\":2,\"qtyDestroyed\":0,\"singleton\":0}],\"zkb\":{\"totalValue\":\"96704" +
            "0612.09\",\"points\":\"268\",\"source\":\"CREST\",\"hash\":\"334d3d3994ac83ec0c810690d597336" +
            "d7ced719b\"}},{\"killID\":\"45864856\",\"solarSystemID\":\"30003726\",\"killTime\":\"2015-04" +
            "-09 18:52:00\",\"moonID\":\"0\",\"victim\":{\"shipTypeID\":\"16238\",\"damageTaken\":\"2880\",\"" +
            "factionName\":\"\",\"factionID\":\"0\",\"allianceName\":\"The Volition Cult\",\"allianceID\":" +
            "\"240835459\",\"corporationName\":\"Volition Cult\",\"corporationID\":\"112702028\",\"chara" +
            "cterName\":\"Containerkai\",\"characterID\":\"1811721987\",\"victim\":\"\"},\"attackers\":[{\"" +
            "characterID\":\"90149862\",\"characterName\":\"Nytoxias\",\"corporationID\":\"98097120\",\"c" +
            "orporationName\":\"ISB Banner Interstellar Operations\",\"allianceID\":\"0\",\"allianceN" +
            "ame\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"3.3475445265637\",\"dam" +
            "ageDone\":\"2188\",\"finalBlow\":\"1\",\"weaponTypeID\":\"27359\",\"shipTypeID\":\"12034\"},{\"c" +
            "haracterID\":\"108115856\",\"characterName\":\"virxens\",\"corporationID\":\"98226285\",\"co" +
            "rporationName\":\"Nexis.\",\"allianceID\":\"99004785\",\"allianceName\":\"TCC.\",\"factionID" +
            "\":\"0\",\"factionName\":\"\",\"securityStatus\":\"-0.3\",\"damageDone\":\"692\",\"finalBlow\":\"0" +
            "\",\"weaponTypeID\":\"27359\",\"shipTypeID\":\"12034\"},{\"characterID\":\"92680254\",\"charac" +
            "terName\":\"BUBAKAR MAHAHA\",\"corporationID\":\"867072006\",\"corporationName\":\"The Rea" +
            "l OC\",\"allianceID\":\"99004887\",\"allianceName\":\"ROC.\",\"factionID\":\"0\",\"factionName" +
            "\":\"\",\"securityStatus\":\"-1.3\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19" +
            "814\",\"shipTypeID\":\"12034\"},{\"characterID\":\"94880891\",\"characterName\":\"Rion Holli" +
            "day\",\"corporationID\":\"98328974\",\"corporationName\":\"Phoenix Naval Academy\",\"allia" +
            "nceID\":\"99004604\",\"allianceName\":\"Phoenix Naval Systems\",\"factionID\":\"0\",\"factio" +
            "nName\":\"\",\"securityStatus\":\"1.3\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\"" +
            ":\"8117\",\"shipTypeID\":\"12032\"},{\"characterID\":\"417481089\",\"characterName\":\"drrave" +
            "ntlwml\",\"corporationID\":\"98082962\",\"corporationName\":\"Severasse Mining\",\"allianc" +
            "eID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"4." +
            "9\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"8117\",\"shipTypeID\":\"12034\"}," +
            "{\"characterID\":\"1392600597\",\"characterName\":\"Angi Tulo\",\"corporationID\":\"9838936" +
            "5\",\"corporationName\":\"Raised By Wolves Inc\",\"allianceID\":\"0\",\"allianceName\":\"\",\"" +
            "factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"0.3\",\"damageDone\":\"0\",\"finalBl" +
            "ow\":\"0\",\"weaponTypeID\":\"8117\",\"shipTypeID\":\"11377\"},{\"characterID\":\"92322922\",\"c" +
            "haracterName\":\"Dr Draxxx\",\"corporationID\":\"98203328\",\"corporationName\":\"Sanctuar" +
            "y of Shadows\",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"" +
            "\",\"securityStatus\":\"-1.7\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19814" +
            "\",\"shipTypeID\":\"12032\"},{\"characterID\":\"95004823\",\"characterName\":\"Rahkesh Harsh" +
            "mallows\",\"corporationID\":\"98378337\",\"corporationName\":\"HC - Thirteen Enterprises" +
            "\",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityS" +
            "tatus\":\"-0.6\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19814\",\"shipTypeI" +
            "D\":\"11377\"},{\"characterID\":\"93401488\",\"characterName\":\"Noria Odunen\",\"corporatio" +
            "nID\":\"98387394\",\"corporationName\":\"100 Deadly Sins\",\"allianceID\":\"0\",\"allianceNa" +
            "me\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":\"3.3\",\"damageDone\":\"0\"," +
            "\"finalBlow\":\"0\",\"weaponTypeID\":\"8117\",\"shipTypeID\":\"12034\"},{\"characterID\":\"9396" +
            "25659\",\"characterName\":\"Ismail Third\",\"corporationID\":\"98385030\",\"corporationNam" +
            "e\":\"Nasheed Appreciation Station\",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\"" +
            ":\"0\",\"factionName\":\"\",\"securityStatus\":\"5\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"wea" +
            "ponTypeID\":\"8117\",\"shipTypeID\":\"12034\"},{\"characterID\":\"92254528\",\"characterName" +
            "\":\"Chris Virens\",\"corporationID\":\"98151305\",\"corporationName\":\"Vril Corp.\",\"alli" +
            "anceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securityStatus\":" +
            "\"-1.1\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19806\",\"shipTypeID\":\"113" +
            "77\"},{\"characterID\":\"94939025\",\"characterName\":\"Peter \'Littlefinger\' Baelish\",\"c" +
            "orporationID\":\"98347696\",\"corporationName\":\"Serious Internet Spaceship Buisness\"" +
            ",\"allianceID\":\"0\",\"allianceName\":\"\",\"factionID\":\"0\",\"factionName\":\"\",\"securitySt" +
            "atus\":\"-0.1\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"8117\",\"shipTypeID\"" +
            ":\"12032\"},{\"characterID\":\"94526200\",\"characterName\":\"Sarah Faye\",\"corporationID\"" +
            ":\"98345210\",\"corporationName\":\"Pandemic Laboratories\",\"allianceID\":\"99004177\",\"a" +
            "llianceName\":\"Shadow\'s Edge Alliance\",\"factionID\":\"0\",\"factionName\":\"\",\"security" +
            "Status\":\"4.8\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"19814\",\"shipTypeI" +
            "D\":\"12038\"},{\"characterID\":\"90974906\",\"characterName\":\"DANGERUS4U DEAD\",\"corpora" +
            "tionID\":\"98296941\",\"corporationName\":\"Freddys Miningcrew\",\"allianceID\":\"99005061" +
            "\",\"allianceName\":\"Requiem for a dream.\",\"factionID\":\"0\",\"factionName\":\"\",\"securi" +
            "tyStatus\":\"-1.9\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"527\",\"shipType" +
            "ID\":\"11963\"},{\"characterID\":\"94522777\",\"characterName\":\"SikulaCZ\",\"corporationID" +
            "\":\"1285989187\",\"corporationName\":\"STARS of BABYLON ALLIANCE\",\"allianceID\":\"46686" +
            "2619\",\"allianceName\":\"CZECH Alliance\",\"factionID\":\"0\",\"factionName\":\"\",\"security" +
            "Status\":\"-2\",\"damageDone\":\"0\",\"finalBlow\":\"0\",\"weaponTypeID\":\"8117\",\"shipTypeID\"" +
            ":\"11377\"}],\"items\":[{\"typeID\":\"3074\",\"flag\":\"29\",\"qtyDropped\":\"1\",\"qtyDestroyed\"" +
            ":\"0\",\"singleton\":\"0\"},{\"typeID\":\"12618\",\"flag\":\"28\",\"qtyDropped\":\"0\",\"qtyDestroy" +
            "ed\":\"38\",\"singleton\":\"0\"},{\"typeID\":\"3074\",\"flag\":\"33\",\"qtyDropped\":\"1\",\"qtyDest" +
            "royed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"3074\",\"flag\":\"30\",\"qtyDropped\":\"1\",\"qtyDe" +
            "stroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"1952\",\"flag\":\"19\",\"qtyDropped\":\"1\",\"qty" +
            "Destroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"23009\",\"flag\":\"5\",\"qtyDropped\":\"0\",\"q" +
            "tyDestroyed\":\"1000\",\"singleton\":\"0\"},{\"typeID\":\"12618\",\"flag\":\"29\",\"qtyDropped\":" +
            "\"0\",\"qtyDestroyed\":\"38\",\"singleton\":\"0\"},{\"typeID\":\"3074\",\"flag\":\"32\",\"qtyDroppe" +
            "d\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"3074\",\"flag\":\"31\",\"qtyDrop" +
            "ped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"12618\",\"flag\":\"30\",\"qtyD" +
            "ropped\":\"0\",\"qtyDestroyed\":\"38\",\"singleton\":\"0\"},{\"typeID\":\"12618\",\"flag\":\"32\",\"" +
            "qtyDropped\":\"38\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"10190\",\"flag\":\"1" +
            "1\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"1952\",\"flag\":" +
            "\"20\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"3074\",\"flag" +
            "\":\"27\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"29011\",\"f" +
            "lag\":\"5\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typeID\":\"3074\",\"" +
            "flag\":\"28\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"},{\"typeID\":\"12618" +
            "\",\"flag\":\"31\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"38\",\"singleton\":\"0\"},{\"typeID\":\"1" +
            "2618\",\"flag\":\"33\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"38\",\"singleton\":\"0\"},{\"typeID" +
            "\":\"31358\",\"flag\":\"92\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0\"},{\"typ" +
            "eID\":\"12618\",\"flag\":\"5\",\"qtyDropped\":\"1447\",\"qtyDestroyed\":\"0\",\"singleton\":\"0\"}," +
            "{\"typeID\":\"31562\",\"flag\":\"93\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleton\":\"0" +
            "\"},{\"typeID\":\"29009\",\"flag\":\"5\",\"qtyDropped\":\"2\",\"qtyDestroyed\":\"0\",\"singleton\":" +
            "\"0\"},{\"typeID\":\"31562\",\"flag\":\"94\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\",\"singleto" +
            "n\":\"0\"},{\"typeID\":\"12618\",\"flag\":\"27\",\"qtyDropped\":\"38\",\"qtyDestroyed\":\"0\",\"sing" +
            "leton\":\"0\"},{\"typeID\":\"5973\",\"flag\":\"21\",\"qtyDropped\":\"1\",\"qtyDestroyed\":\"0\",\"si" +
            "ngleton\":\"0\"},{\"typeID\":\"10190\",\"flag\":\"12\",\"qtyDropped\":\"0\",\"qtyDestroyed\":\"1\"," +
            "\"singleton\":\"0\"}],\"zkb\":{\"totalValue\":\"11067192.17\",\"points\":\"4\",\"source\":\"API\"," +
            "\"hash\":\"945c0e5873b5bb99fda4df5fb3875029df950db0\"}},{\"killID\":45864282,\"solarSys" +
            "temID\":30003726,\"killTime\":\"2015-04-09 18:32:00\",\"moonID\":0,\"victim\":{\"shipTypeI" +
            "D\":602,\"characterID\":90283357,\"characterName\":\"Pyroxim\",\"corporationID\":98178435" +
            ",\"corporationName\":\"Lauren Abbey Industries\",\"allianceID\":240835459,\"allianceNam" +
            "e\":\"The Volition Cult\",\"factionID\":0,\"factionName\":\"\",\"damageTaken\":1791},\"attac" +
            "kers\":[{\"characterID\":94220967,\"characterName\":\"Rar Fox\",\"corporationID\":9828868" +
            "3,\"corporationName\":\"Umbra Syndicate\",\"allianceID\":0,\"allianceName\":\"\",\"factionI" +
            "D\":0,\"factionName\":\"\",\"securityStatus\":0.7,\"damageDone\":605,\"finalBlow\":1,\"weapo" +
            "nTypeID\":27345,\"shipTypeID\":12032},{\"characterID\":93401488,\"characterName\":\"Nori" +
            "a Odunen\",\"corporationID\":98387394,\"corporationName\":\"100 Deadly Sins\",\"alliance" +
            "ID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":3.3,\"dam" +
            "ageDone\":371,\"finalBlow\":0,\"weaponTypeID\":27359,\"shipTypeID\":12034},{\"characterI" +
            "D\":93574604,\"characterName\":\"Tipa Riot\",\"corporationID\":1000168,\"corporationName" +
            "\":\"Federal Navy Academy\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"faction" +
            "Name\":\"\",\"securityStatus\":-2.2,\"damageDone\":228,\"finalBlow\":0,\"weaponTypeID\":273" +
            "39,\"shipTypeID\":12038},{\"characterID\":92322922,\"characterName\":\"Dr Draxxx\",\"corp" +
            "orationID\":98203328,\"corporationName\":\"Sanctuary of Shadows\",\"allianceID\":0,\"all" +
            "ianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-1.7,\"damageDone\":" +
            "221,\"finalBlow\":0,\"weaponTypeID\":27345,\"shipTypeID\":12032},{\"characterID\":922545" +
            "28,\"characterName\":\"Chris Virens\",\"corporationID\":98151305,\"corporationName\":\"Vr" +
            "il Corp.\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"secur" +
            "ityStatus\":-1.1,\"damageDone\":213,\"finalBlow\":0,\"weaponTypeID\":27351,\"shipTypeID\"" +
            ":11377},{\"characterID\":94522777,\"characterName\":\"SikulaCZ\",\"corporationID\":12859" +
            "89187,\"corporationName\":\"STARS of BABYLON ALLIANCE\",\"allianceID\":466862619,\"alli" +
            "anceName\":\"CZECH Alliance\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-2,\"d" +
            "amageDone\":143,\"finalBlow\":0,\"weaponTypeID\":27351,\"shipTypeID\":11377},{\"characte" +
            "rID\":95145225,\"characterName\":\"ILK Baddies\",\"corporationID\":98354230,\"corporatio" +
            "nName\":\"Voidlight Consortium\",\"allianceID\":99005190,\"allianceName\":\"Interstellar" +
            " Solutions\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-3.2,\"damageDone\":10" +
            ",\"finalBlow\":0,\"weaponTypeID\":33468,\"shipTypeID\":33468},{\"characterID\":90149862," +
            "\"characterName\":\"Nytoxias\",\"corporationID\":98097120,\"corporationName\":\"ISB Banne" +
            "r Interstellar Operations\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"facti" +
            "onName\":\"\",\"securityStatus\":3.3,\"damageDone\":0,\"finalBlow\":0,\"weaponTypeID\":3244" +
            ",\"shipTypeID\":12034},{\"characterID\":939625659,\"characterName\":\"Ismail Third\",\"co" +
            "rporationID\":98385030,\"corporationName\":\"Nasheed Appreciation Station\",\"alliance" +
            "ID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":5,\"damag" +
            "eDone\":0,\"finalBlow\":0,\"weaponTypeID\":8117,\"shipTypeID\":12034},{\"characterID\":94" +
            "939025,\"characterName\":\"Peter \'Littlefinger\' Baelish\",\"corporationID\":98347696,\"" +
            "corporationName\":\"Serious Internet Spaceship Buisness\",\"allianceID\":0,\"allianceN" +
            "ame\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-0.1,\"damageDone\":0,\"fin" +
            "alBlow\":0,\"weaponTypeID\":8117,\"shipTypeID\":12032},{\"characterID\":94526200,\"chara" +
            "cterName\":\"Sarah Faye\",\"corporationID\":98345210,\"corporationName\":\"Pandemic Labo" +
            "ratories\",\"allianceID\":99004177,\"allianceName\":\"Shadow\'s Edge Alliance\",\"faction" +
            "ID\":0,\"factionName\":\"\",\"securityStatus\":4.8,\"damageDone\":0,\"finalBlow\":0,\"weapon" +
            "TypeID\":19814,\"shipTypeID\":12038},{\"characterID\":93051312,\"characterName\":\"Romaz" +
            " Chechen\",\"corporationID\":98273077,\"corporationName\":\"boobies and kittens\",\"alli" +
            "anceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-1.3" +
            ",\"damageDone\":0,\"finalBlow\":0,\"weaponTypeID\":2420,\"shipTypeID\":12038},{\"characte" +
            "rID\":1392600597,\"characterName\":\"Angi Tulo\",\"corporationID\":98389365,\"corporatio" +
            "nName\":\"Raised By Wolves Inc\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"fa" +
            "ctionName\":\"\",\"securityStatus\":0.3,\"damageDone\":0,\"finalBlow\":0,\"weaponTypeID\":8" +
            "117,\"shipTypeID\":11377},{\"characterID\":95004823,\"characterName\":\"Rahkesh Harshma" +
            "llows\",\"corporationID\":98378337,\"corporationName\":\"HC - Thirteen Enterprises\",\"a" +
            "llianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-" +
            "0.6,\"damageDone\":0,\"finalBlow\":0,\"weaponTypeID\":8117,\"shipTypeID\":11377},{\"chara" +
            "cterID\":90974906,\"characterName\":\"DANGERUS4U DEAD\",\"corporationID\":98296941,\"cor" +
            "porationName\":\"Freddys Miningcrew\",\"allianceID\":99005061,\"allianceName\":\"Requiem" +
            " for a dream.\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":-1.9,\"damageDone\"" +
            ":0,\"finalBlow\":0,\"weaponTypeID\":527,\"shipTypeID\":11963},{\"characterID\":417481089" +
            ",\"characterName\":\"drraventlwml\",\"corporationID\":98082962,\"corporationName\":\"Seve" +
            "rasse Mining\",\"allianceID\":0,\"allianceName\":\"\",\"factionID\":0,\"factionName\":\"\",\"s" +
            "ecurityStatus\":4.9,\"damageDone\":0,\"finalBlow\":0,\"weaponTypeID\":19814,\"shipTypeID" +
            "\":12034},{\"characterID\":94920709,\"characterName\":\"capt boemernl\",\"corporationID\"" +
            ":98249462,\"corporationName\":\"Unkindness Incorporated\",\"allianceID\":99005186,\"all" +
            "ianceName\":\"No Not Believing\",\"factionID\":0,\"factionName\":\"\",\"securityStatus\":3." +
            "8,\"damageDone\":0,\"finalBlow\":0,\"weaponTypeID\":3244,\"shipTypeID\":33468}],\"items\":" +
            "[{\"typeID\":22291,\"flag\":11,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"type" +
            "ID\":8089,\"flag\":27,\"qtyDropped\":1,\"qtyDestroyed\":0,\"singleton\":0},{\"typeID\":8089" +
            ",\"flag\":30,\"qtyDropped\":1,\"qtyDestroyed\":0,\"singleton\":0},{\"typeID\":5973,\"flag\":" +
            "19,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":210,\"flag\":28,\"qtyDr" +
            "opped\":0,\"qtyDestroyed\":39,\"singleton\":0},{\"typeID\":31586,\"flag\":94,\"qtyDropped\"" +
            ":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":8089,\"flag\":29,\"qtyDropped\":0,\"qtyD" +
            "estroyed\":1,\"singleton\":0},{\"typeID\":31752,\"flag\":92,\"qtyDropped\":0,\"qtyDestroye" +
            "d\":1,\"singleton\":0},{\"typeID\":210,\"flag\":29,\"qtyDropped\":0,\"qtyDestroyed\":39,\"si" +
            "ngleton\":0},{\"typeID\":8089,\"flag\":28,\"qtyDropped\":1,\"qtyDestroyed\":0,\"singleton\"" +
            ":0},{\"typeID\":210,\"flag\":27,\"qtyDropped\":39,\"qtyDestroyed\":0,\"singleton\":0},{\"ty" +
            "peID\":22291,\"flag\":12,\"qtyDropped\":0,\"qtyDestroyed\":1,\"singleton\":0},{\"typeID\":2" +
            "10,\"flag\":5,\"qtyDropped\":1854,\"qtyDestroyed\":0,\"singleton\":0},{\"typeID\":8481,\"fl" +
            "ag\":20,\"qtyDropped\":0,\"qtyDestroyed\":1,\"single")]
        public string TestThis {
            get {
                return ((string)(this["TestThis"]));
            }
        }
    }
}
