//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public System.Guid Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Data { get; set; }
        public string Type { get; set; }
    }
}
