//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryNotifications = new HashSet<CategoryNotification>();
            this.CategoryPermissionForRoles = new HashSet<CategoryPermissionForRole>();
            this.Topics = new HashSet<Topic>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> Category_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Slug { get; set; }
        public int SortOrder { get; set; }
        public bool IsLocked { get; set; }
        public bool ModerateTopics { get; set; }
        public bool ModeratePosts { get; set; }
        public string PageTitle { get; set; }
        public string MetaDescription { get; set; }
        public string Path { get; set; }
        public string Colour { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<CategoryNotification> CategoryNotifications { get; set; }
        public virtual ICollection<CategoryPermissionForRole> CategoryPermissionForRoles { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
