//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocaleStringResource
    {
        public System.Guid Id { get; set; }
        public System.Guid Language_Id { get; set; }
        public System.Guid LocaleResourceKey_Id { get; set; }
        public string ResourceValue { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual LocaleResourceKey LocaleResourceKey { get; set; }
    }
}
