//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipUser
    {
        public MembershipUser()
        {
            this.BadgeTypeTimeLastCheckeds = new HashSet<BadgeTypeTimeLastChecked>();
            this.CategoryNotifications = new HashSet<CategoryNotification>();
            this.MembershipUser_Badge = new HashSet<MembershipUser_Badge>();
            this.MembershipUserPoints = new HashSet<MembershipUserPoint>();
            this.MembershipUsersInRoles = new HashSet<MembershipUsersInRole>();
            this.Polls = new HashSet<Poll>();
            this.PollVotes = new HashSet<PollVote>();
            this.Posts = new HashSet<Post>();
            this.PrivateMessages = new HashSet<PrivateMessage>();
            this.PrivateMessages1 = new HashSet<PrivateMessage>();
            this.Topics = new HashSet<Topic>();
            this.TopicNotifications = new HashSet<TopicNotification>();
            this.Votes = new HashSet<Vote>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public int FailedPasswordAnswerAttempt { get; set; }
        public string Slug { get; set; }
        public string Comment { get; set; }
        public string Signature { get; set; }
        public Nullable<int> Age { get; set; }
        public string Location { get; set; }
        public string Website { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string Avatar { get; set; }
        public string FacebookAccessToken { get; set; }
        public Nullable<long> FacebookId { get; set; }
        public string TwitterAccessToken { get; set; }
        public string TwitterId { get; set; }
        public string GoogleAccessToken { get; set; }
        public string GoogleId { get; set; }
        public Nullable<bool> IsExternalAccount { get; set; }
        public Nullable<bool> TwitterShowFeed { get; set; }
        public Nullable<bool> DisableEmailNotifications { get; set; }
        public Nullable<bool> DisablePosting { get; set; }
        public Nullable<bool> DisablePrivateMessages { get; set; }
        public Nullable<bool> DisableFileUploads { get; set; }
        public Nullable<System.DateTime> LoginIdExpires { get; set; }
        public string MiscAccessToken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
    
        public virtual ICollection<BadgeTypeTimeLastChecked> BadgeTypeTimeLastCheckeds { get; set; }
        public virtual ICollection<CategoryNotification> CategoryNotifications { get; set; }
        public virtual ICollection<MembershipUser_Badge> MembershipUser_Badge { get; set; }
        public virtual ICollection<MembershipUserPoint> MembershipUserPoints { get; set; }
        public virtual ICollection<MembershipUsersInRole> MembershipUsersInRoles { get; set; }
        public virtual ICollection<Poll> Polls { get; set; }
        public virtual ICollection<PollVote> PollVotes { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages1 { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual ICollection<TopicNotification> TopicNotifications { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
