//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipRole
    {
        public MembershipRole()
        {
            this.CategoryPermissionForRoles = new HashSet<CategoryPermissionForRole>();
            this.MembershipUsersInRoles = new HashSet<MembershipUsersInRole>();
            this.Settings = new HashSet<Setting>();
        }
    
        public System.Guid Id { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<CategoryPermissionForRole> CategoryPermissionForRoles { get; set; }
        public virtual ICollection<MembershipUsersInRole> MembershipUsersInRoles { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
    }
}
