//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.CategoryPermissionForRoles = new HashSet<CategoryPermissionForRole>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsGlobal { get; set; }
    
        public virtual ICollection<CategoryPermissionForRole> CategoryPermissionForRoles { get; set; }
    }
}
