//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollAnswer
    {
        public PollAnswer()
        {
            this.PollVotes = new HashSet<PollVote>();
        }
    
        public System.Guid Id { get; set; }
        public string Answer { get; set; }
        public System.Guid Poll_Id { get; set; }
    
        public virtual Poll Poll { get; set; }
        public virtual ICollection<PollVote> PollVotes { get; set; }
    }
}
