//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid MembershipUser_Id { get; set; }
        public string PostContent { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int VoteCount { get; set; }
        public System.Guid Topic_Id { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public bool IsSolution { get; set; }
        public Nullable<bool> IsTopicStarter { get; set; }
        public Nullable<bool> FlaggedAsSpam { get; set; }
        public string IpAddress { get; set; }
        public Nullable<bool> Pending { get; set; }
    
        public virtual MembershipUser MembershipUser { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
