//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessage
    {
        public System.Guid Id { get; set; }
        public System.Guid UserTo_Id { get; set; }
        public System.Guid UserFrom_Id { get; set; }
        public System.DateTime DateSent { get; set; }
        public string Message { get; set; }
        public bool IsRead { get; set; }
        public bool IsSentMessage { get; set; }
    
        public virtual MembershipUser MembershipUser { get; set; }
        public virtual MembershipUser MembershipUser1 { get; set; }
    }
}
