//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class r3mus_ForumDBEntities : DbContext
    {
        public r3mus_ForumDBEntities()
            : base("name=r3mus_ForumDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<BadgeTypeTimeLastChecked> BadgeTypeTimeLastCheckeds { get; set; }
        public virtual DbSet<BannedEmail> BannedEmails { get; set; }
        public virtual DbSet<BannedWord> BannedWords { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryNotification> CategoryNotifications { get; set; }
        public virtual DbSet<CategoryPermissionForRole> CategoryPermissionForRoles { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Favourite> Favourites { get; set; }
        public virtual DbSet<GlobalPermissionForRole> GlobalPermissionForRoles { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LocaleResourceKey> LocaleResourceKeys { get; set; }
        public virtual DbSet<LocaleStringResource> LocaleStringResources { get; set; }
        public virtual DbSet<MembershipRole> MembershipRoles { get; set; }
        public virtual DbSet<MembershipUser> MembershipUsers { get; set; }
        public virtual DbSet<MembershipUser_Badge> MembershipUser_Badge { get; set; }
        public virtual DbSet<MembershipUserPoint> MembershipUserPoints { get; set; }
        public virtual DbSet<MembershipUsersInRole> MembershipUsersInRoles { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<PollAnswer> PollAnswers { get; set; }
        public virtual DbSet<PollVote> PollVotes { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PrivateMessage> PrivateMessages { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<Topic_Tag> Topic_Tag { get; set; }
        public virtual DbSet<TopicNotification> TopicNotifications { get; set; }
        public virtual DbSet<TopicTag> TopicTags { get; set; }
        public virtual DbSet<UploadedFile> UploadedFiles { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    }
}
