//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic_Tag
    {
        public System.Guid Id { get; set; }
        public System.Guid Topic_Id { get; set; }
        public System.Guid TopicTag_Id { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual TopicTag TopicTag { get; set; }
    }
}
