//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteUpdateBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicTag
    {
        public TopicTag()
        {
            this.Topic_Tag = new HashSet<Topic_Tag>();
        }
    
        public System.Guid Id { get; set; }
        public string Tag { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<Topic_Tag> Topic_Tag { get; set; }
    }
}
