// <auto-generated />
namespace r3mus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMailer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMailer));
        
        string IMigrationMetadata.Id
        {
            get { return "201505071232335_AddMailer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
